CUTOFF_MATCH_THRESHOLD = 0.95

RESAMPLE_WIDTH = 512

MIN_RESCALE_WIDTH = 70

MAX_TEST_SAMPLE_WIDTH_RATIO = 0.9

MAX_TEST_SAMPLE_HEIGHT_RATIO = 0.9

MIN_TEST_SAMPLE_WIDTH = 100

MIN_TEST_SAMPLE_HEIGHT = 50

ROOT_SAMPLES_PATH = './images/'

# end of file
